### PR TITLE
added missing QPainterPath includes

### PR DESCRIPTION
**Pull request by frostworx**
## Summary
in order to compile correctly under arch linux, those includes are required. fixes https://github.com/stitchEm/stitchEm/issues/117

### CODE REVIEW

**Comment by w-m** [comment]
@jeremad any ideas why the build isn't running on this PR?

**Comment by frostworx** [comment]
maybe related?:
https://github.com/PIVX-Project/PIVX/pull/1683

**Comment by arpu** [comment]
tested on fedora 33 and this patch looks fine! thx

**Review by w-m — APPROVED** [review]

**Comment by frostworx** [comment]
\o/

**Comment by w-m** [comment]
Thanks for providing the PR!

**Pull request merged**
