### PR TITLE
OpenCV4 support

### PR DESCRIPTION
**Pull request by klem23**
OpenCV4 support : change old C definition to standard c++ one in use
the old definition still exist in imgproc.c_types.h

## Summary
OpenCV 4 made some changes regarding C definition in imgproc
I update them. It seems to work....

## Review
Should be compiled on Mac and Windows also.
I don't know if we need to check compatibility with OpenCV3

## Test coverage
- [ ] code already covered by the following tests:
- [ ] a new unit test is provided with this change set
- [ ] a new command line test is provided with this change set
- [ ] a new squish test is provided with this change set
- [ ] no test needed: ok but why?

### CODE REVIEW

**Comment by w-m** [comment]
Fixes https://github.com/stitchEm/stitchEm/issues/62.

**Comment by w-m** [comment]
OpenCV 4 from MacPorts depends on https://github.com/opencv/ade and causes a linking error to `-lade`.

**Comment by jeremad** [comment]
Let's wait a final 2.4 release before merging this, but it looks good!

**Comment by klem23** [comment]
Yes at least no regression with opencv 3...

**Comment by jeremad** [comment]
I'll test on windows, but let's not block that

**Pull request merged**
